# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: cddc784e9719a099559784324d54174064ff1bd7d6b4163f3965d876bbb1279e787f434e0e71aade38147b3466b564a6836902a23da2c26b65aaac242547e4db

test:
  secret_key_base: 74bdce9242b4bd7bb7b72ddabcf80c83f752e86ab39b1ebc79ac3a175758e47f4129a31532e90c4c7571f4241e12f93f84015da52640cc7f2f3ee28fffe595b2

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
